#!/usr/bin/env sh
#
# Modified and adapted from the original at https://github.com/vivien/i3blocks
# Copyright (C) 2024 Ludovico Deponte <ludovico.deponte@proton.me>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

TYPE="${BLOCK_INSTANCE:-mem}"
PERCENT="${PERCENT:-true}"

CRIT_C="${signal_crit}"
WARN_C="${signal_warn}"
MILD_C="${signal_mild}"
DEFA_C="${signal_defa}"

awk -v type=$TYPE -v percent=$PERCENT -v crit_c=$CRIT_C -v warn_c=$WARN_C -v mild_c=$MILD_C -v defa_c=$DEFA_C '
/^MemTotal:/ {
	mem_total=$2
}
/^MemFree:/ {
	mem_free=$2
}
/^Buffers:/ {
	mem_free+=$2
}
/^Cached:/ {
	mem_free+=$2
}
/^SwapTotal:/ {
	swap_total=$2
}
/^SwapFree:/ {
	swap_free=$2
}
END {
	if (type == "swap") {
		free=swap_free/1024/1024
		used=(swap_total-swap_free)/1024/1024
		total=swap_total/1024/1024
	} else {
		free=mem_free/1024/1024
		used=(mem_total-mem_free)/1024/1024
		total=mem_total/1024/1024
	}

	pct=0
	if (total > 0) {
		pct=used/total*100
	}

	# short text
	printf("%.f%%\n", pct)

	# full text
	if (percent == "true" ) {
		printf("%.1fG/%.1fG (%.f%%)\n", used, total, pct)
	} else {
		printf("%.1fG/%.1fG\n", used, total)
	}

	# color
	if (pct > 90) {
		print(crit_c)
	} else if (pct > 70) {
		print(warn_c)
	} else if (pct > 50) {
		print(mild_c)
	} else {
		print(defa_c)
	}
}
' /proc/meminfo
