#!/usr/bin/env sh
#
# Status bar module for disk space. $1 is drive mountpoint, $2 is optional icon, otherwise mountpoint will displayed
# inspired by https://github.com/tallguyjenks/.dotfiles/blob/master/scripts/.local/bin/statusbar/disk
#
# Copyright (C) 2024 Ludovico Deponte <ludovico.deponte@proton.me>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

[ -z "$1" ] && exit

icon="$2"
[ -z "$2" ] && icon="$1"

case $BLOCK_BUTTON in
	1) pgrep -x dunst >/dev/null && notify-send " Disk space" "$(df -h --output=target,used,size)" ;;
	3) pgrep -x dunst >/dev/null && notify-send " Disk module" "\- Shows used hard drive space.
- Click to show all disk info." ;;
esac

echo $(df -h $1 | awk ' /[0-9]/ {print substr( $3,1, length($3)-1) "/" $2}')
percent=$(df -h $1 | awk ' /[0-9]/ {print substr( $5,1, length($5)-1)}')
echo $percent
if echo $percent 80 | awk '{exit !( $1 > $2)}'; then
    echo "#signal_crit"
elif echo $percent 65 | awk '{exit !( $1 > $2)}'; then
    echo "#signal_warn"
elif echo $percent 50 | awk '{exit !( $1 > $2)}'; then
    echo "$signal_mild"
else
    echo "$signal_defa"
fi
