#!/bin/sh
#
# Simple script to display a button shortcut for interfacing my home server.
# Copyright (C) 2024 Ludovico Deponte <ludovico.deponte@proton.me>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

COMMAND=$(setxkbmap -query | grep layout | awk '{print $2}')

case "$COMMAND" in
	"us") setxkbmap "it"; LAYOUT="IT";;
	"it") setxkbmap "us"; LAYOUT="";;
	*) LAYOUT="??";;
esac

echo $LAYOUT
echo $LAYOUT
echo $lh___green_0
