#!/usr/bin/env sh
#
# Simple script to show the CPU temperature formatted for use with i3blocks
# Modified and adapted from the original at https://github.com/BrodieRobertson/scripts/blob/master/i3/i3temp
# Copyright (C) 2024 Ludovico Deponte <ludovico.deponte@proton.me>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

temp=$(acpi -t | sed 's/.*, //;s/ degrees //;s/C//')
echo $temp°C
echo $temp°C

if echo $temp 80 | awk '{exit !( $1 > $2)}'; then
    echo "$signal_crit"
elif echo $temp 65 | awk '{exit !( $1 > $2)}'; then
    echo "$signal_warn"
elif echo $temp 50 | awk '{exit !( $1 > $2)}'; then
    echo "$signal_mild"
else
    echo "$signal_defa"
fi

