#!/usr/bin/env bash
# Simple script to show the current WiFi SSID, colors the name based on signal quality
# quality is based on dBm received, it is not the Signal to Noise Ratio (SNR) reported
# with '/sbin/iwlist scan' 
# pass the interface as instance=INTERFACE in the block definition (in i3blocks/config)
# a modified version of default wifi/wifi

#------------------------------------------------------------------------
if [ -z "$INTERFACE" ] ; then
    INTERFACE="${BLOCK_INSTANCE:-wlan0}"
fi
#------------------------------------------------------------------------
# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
[[ ! -d /sys/class/net/${INTERFACE}/wireless ]] && exit

# If the wifi interface exists but no connection is active, "down" shall be displayed.
if [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]]; then
    echo "down"
    echo "down"
    echo $signal_crit
else
#------------------------------------------------------------------------

QUALITY=$(/sbin/iw dev ${INTERFACE} link | grep 'dBm$'| grep -Eoe '-[0-9]{2}' |awk '{print  ($1 > -50 ? 100 :($1 < -100 ? 0 : ($1+100)*2))}')

# full and short text
/sbin/iwgetid | awk '{print $1 " "  substr( $2,8,length($2)-8)}' | { read iface ssid ; echo $ssid; echo $ssid; }

# color
if [[ $QUALITY -ge 80 ]]; then
    echo $signal_defa
elif [[ $QUALITY -ge 60 ]]; then
    echo $signal_mild
elif [[ $QUALITY -ge 40 ]]; then
    echo $signal_warn
else
    echo $signal_crit
fi
fi

case $BLOCK_BUTTON in
  1) i3-msg "exec ~/.config/rofi/scripts/wifi.sh"
esac